# Generated by Django 5.0.8 on 2024-08-10 13:01

import snap_buy.core.utils.json_serializer
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "private_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=snap_buy.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=snap_buy.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("local", "local"), ("thirdparty", "thirdparty")],
                        default="local",
                        max_length=60,
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=256)),
                ("about_app", models.TextField(blank=True)),
                ("data_privacy", models.TextField(blank=True)),
                ("data_privacy_url", models.URLField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("support_url", models.URLField(blank=True)),
                ("configuration_url", models.URLField(blank=True)),
                ("app_url", models.URLField(blank=True)),
                ("manifest_url", models.URLField(blank=True)),
                ("version", models.CharField(blank=True, max_length=60)),
                ("audience", models.CharField(blank=True, max_length=256)),
                ("is_installed", models.BooleanField(default=True)),
                ("author", models.CharField(blank=True, max_length=60)),
                (
                    "brand_logo_default",
                    models.ImageField(
                        blank=True, null=True, upload_to="app-brand-data"
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
                "permissions": (
                    ("manage_apps", "Manage apps"),
                    ("manage_observability", "Manage observability"),
                ),
                "abstract": False,
            },
        ),
    ]
