# Generated by Django 5.0.8 on 2024-08-16 11:21

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
        ("permission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this app.",
                related_name="app_set",
                related_query_name="app",
                to="permission.permission",
            ),
        ),
        migrations.AddIndex(
            model_name="app",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="app_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="app",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="app_meta_idx"
            ),
        ),
    ]
