# Generated by Django 5.0.8 on 2024-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="about_app",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="app_url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="audience",
            field=models.CharField(blank=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="author",
            field=models.CharField(blank=True, default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="configuration_url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="data_privacy",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="data_privacy_url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="homepage_url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="manifest_url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="support_url",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="version",
            field=models.CharField(blank=True, default=1, max_length=60),
            preserve_default=False,
        ),
    ]
