# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --reuse-db --import-mode=importlib"
python_files = ["tests.py", "test_*.py"]

# ==== Coverage ====
[tool.coverage.run]
include = ["snap_buy/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]

# ==== mypy ====
[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings.test"

# ==== djLint ====
[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/djlint/djLint/issues/687
ignore = "H006,H030,H031,T002"
include = "H017,H035"
indent = 2
max_line_length = 119
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

lint.extend-select = ["D", "I", "ISC002", "PIE", "PT", "T20", "UP"]
lint.ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "D202",
  "D203",
  "D206",
  "D213",
  "D407",
  "PT019",
]
target-version = "py312"

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
  "*/migrations/*.py",
  "staticfiles/*",
]
# Same as Django: https://github.com/cookiecutter/cookiecutter-django/issues/4792.
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "YTT",
  # "ANN", # flake8-annotations: we should support this in the future but 100+ errors atm
  "ASYNC",
  "S",
  "BLE",
  "FBT",
  "B",
  "A",
  "COM",
  "C4",
  "DTZ",
  "T10",
  "DJ",
  "EM",
  "EXE",
  "FA",
  'ISC',
  "ICN",
  "G",
  'INP',
  'PIE',
  "T20",
  'PYI',
  'PT',
  "Q",
  "RSE",
  "RET",
  "SLF",
  "SLOT",
  "SIM",
  "TID",
  "TCH",
  "INT",
  # "ARG", # Unused function argument
  "PTH",
  "ERA",
  "PD",
  "PGH",
  "PL",
  "TRY",
  "FLY",
  # "NPY",
  # "AIR",
  "PERF",
  # "FURB",
  # "LOG",
  "RUF",
]
ignore = [
  "S101",   # Use of assert detected https://docs.astral.sh/ruff/rules/assert/
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
  "SIM102", # sometimes it's better to nest
  "UP038",  # Checks for uses of isinstance/issubclass that take a tuple
  # of types for comparison.
  # Deactivated because it can make the code slow:
  # https://github.com/astral-sh/ruff/issues/7871
  "EXE002", # https://docs.astral.sh/ruff/rules/shebang-missing-executable-file/
  "E501",   # https://docs.astral.sh/ruff/rules/line-too-long/
  "G004",   # https://docs.astral.sh/ruff/rules/logging-f-string/
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# The fixes in extend-unsafe-fixes will require
# provide the `--unsafe-fixes` flag when fixing.
extend-unsafe-fixes = ["UP038"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
force-single-line = true
known-first-party = ["snap-buy"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "saleor"
version = "3.20.0-a.0"
description = "A modular, high performance, headless e-commerce platform built with Python, GraphQL, Django, and React."
authors = ["Saleor Commerce <hello@saleor.io>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://saleor.io/"
repository = "https://github.com/saleor/saleor"
documentation = "https://docs.saleor.io/"

[tool.poetry.dependencies]
python = "~3.12"
Adyen = "^4.0.0"
aniso8601 = "^7.0.0"
asgiref = "^3.7.2"
Authlib = "^1.3.1"
authorizenet = "^1.1.3"
azure-common = "^1.1.28"
azure-storage-blob = "^12.12.0"
azure-storage-common = "^2.1.0"
babel = ">=2.8,<2.15"
boto3 = "^1.28"
botocore = "^1.31"
braintree = ">=4.2,<4.27"
cryptography = "^42.0.5"
dj-database-url = "^2"
dj-email-url = "^1"
django = { version = "^3.2.24", extras = ["bcrypt"] }
django-cache-url = "^3.1.2"
django-celery-beat = "^2.2.1"
django-countries = "^7.2"
django-filter = "^23.1"
django-measurement = "^3.0"
django-mptt = "^0"
django-phonenumber-field = ">=4,<8"
django-prices = "^2.3"
django-redis = "^5.0.0"
django-stubs-ext = "^4.2.1"
draftjs-sanitizer = "^1.0.0"
faker = ">=4.1,<24.0"
google-cloud-pubsub = ">=1.7,<3.0"
google-cloud-storage = "^2.0.0"
google-i18n-address = "^3.1.0"
graphene = "<3.0"
graphql-core = "^2.3.2"
graphql-relay = "^2.0.1"
gunicorn = "^22.0.0"
html2text = "^2020.1.16"
html-to-draftjs = "^1.0.1"
jaeger-client = "^4.5.0"
lxml = "^4.9.3"
markdown = "^3.1.1"
measurement = "^3.2.2"
micawber = "^0.5.2"
oauthlib = "^3.1"
opentracing = "^2.3.0"
petl = "1.7.14"
phonenumberslite = "^8.12.25"
pillow = "^10.1.0"
pillow-avif-plugin = "^1.3.1"
posuto = "^2023.2.0"
prices = "^1.0"
promise = "^2.3"
psycopg2 = "^2.8.3"
pybars3 = "^0.9.7"
pyjwt = "2.5.0"                                          # Version 2.6.0 changed iat validation which causes tests to fail: https://github.com/saleor/saleor/issues/11047
python-dateutil = "^2.8.2"
python-http-client = "^3.3.7"
python-json-logger = ">=0.1.11,<2.1.0"
pytimeparse = "^1.1.8"
pytz = "^2024.1"
razorpay = "^1.2"
redis = "^5.0.1"
requests = "^2.22"
requests-hardened = "1.0.0b3"
Rx = "^1.6.3"
semantic-version = "^2.10.0"
sendgrid = "^6.7.1"
sentry-sdk = "1.40.5"                                    # https://github.com/getsentry/sentry-python/issues/2554
stripe = "^3.0.0"
text-unidecode = "^1.2"
urllib3 = "^1.26.18"
uvicorn = { extras = ["standard"], version = "^0.23.1" }
weasyprint = ">=53.0"                                    # libpango >=1.44 is required

[tool.poetry.dependencies.celery]
version = ">=4.4.5,<6.0.0"
extras = ["redis"]

[tool.poetry.dependencies.django-storages]
version = "^1.11"
extras = ["google"]

[tool.poetry.dependencies.python-magic]
version = "^0.4.27"
markers = "sys_platform != 'win32'"

[tool.poetry.dependencies.python-magic-bin]
version = "^0.4.14"
platform = "win32"

[tool.poetry.group.dev.dependencies]
before_after = "^1.0.1"
coverage = "^7.2"
deptry = "^0.12.0"
django-debug-toolbar = "^4.0"
django-debug-toolbar-request-history = "^0"
django-graphiql-debug-toolbar = "^0.2.0"
django-extensions = "^3.1.2"
django-stubs = "^4.2.6"
fakeredis = "^2.10"
freezegun = "^1"
mypy = "1.6.1"
mypy-extensions = "^1.0.0"
openpyxl = "^3.0.3"
pre-commit = "^3.4"
pytest = "^8.0.0"
pytest-asyncio = "^0.21.0"
pytest-celery = "^0.0.0"
pytest-cov = "^4.0.0"
pytest-django = "4.8.0"
pytest-django-queries = "~1.2"
pytest-memray = "^1.5.0"
pytest-mock = "^3.6.1"
pytest-recording = "^0.13.0"
pytest-socket = "^0.7.0"
pytest-xdist = "^3.0.2"
pywatchman = "^2.0.0"
ruff = "^0.3.0"
semgrep = ">=1.34.0"
types-certifi = "^2021.10.8"
types-freezegun = "^1.1.7"
types-mock = "^5.0.0.5"
types-pkg-resources = "^0.1.3"
types-python-dateutil = "^2.8.19"
types-pytz = "^2024.1.0"
types-redis = "^4.6.0"
types-requests = "^2.31.0"
types-six = "^1.16.17"
vcrpy = ">=4.0,<5.0"

[tool.deptry]
extend_exclude = ["conftest\\.py", ".*/conftest\\.py", ".*/tests/.*"]

[tool.deptry.package_module_name_map]
graphql-core = "graphql"
pillow = "PIL"
python-magic-bin = "magic"

[tool.deptry.per_rule_ignores]
DEP001 = ["pkg_resources"]
DEP002 = [
  "azure-common",
  "azure-storage-blob",
  "azure-storage-common",
  "django-redis",
  "gunicorn",
  "psycopg2",
]
DEP004 = ["debug_toolbar", "graphiql_debug_toolbar"]


[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
