# Generated by Django 5.0.8 on 2024-08-09 15:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import snap_buy.core.db.fields
import snap_buy.core.utils.json_serializer
import snap_buy.core.weight
import typing
from decimal import Decimal
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
    ]
