# Generated by Django 5.0.8 on 2024-08-09 17:44

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0001_initial"),
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productchannellisting",
            index=models.Index(
                fields=["published_at"], name="product_pro_publish_a3c049_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productchannellisting",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["discounted_price_amount"],
                name="product_pro_discoun_3145f3_btree",
            ),
        ),
    ]
