# Generated by Django 5.0.8 on 2024-08-09 17:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0001_initial"),
        ("discount", "0003_promotionrule_gifts_promotionrule_variants_and_more"),
        (
            "product",
            "0003_productchannellisting_product_pro_publish_a3c049_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "slug"],
                name="collection_search_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="productvariantchannellisting",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["price_amount", "channel_id"],
                name="product_pro_price_a_fb6bd3_gin",
            ),
        ),
    ]
