# Generated by Django 5.0.8 on 2024-08-09 17:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_collection_collection_search_gin_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="category_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="category_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "slug", "description_plaintext"],
                name="category_search_name_slug_gin",
                opclasses=["gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["updated_at"], name="updated_at_idx"
            ),
        ),
    ]
