# Generated by Django 5.0.8 on 2024-08-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0003_productchannellisting_product_pro_publish_a3c049_idx_and_more",
        ),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="product_variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="product.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("warehouse", "product_variant")},
        ),
    ]
