# Generated by Django 5.0.8 on 2024-08-09 15:00

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        ("product", "0001_initial"),
        ("shipping", "0001_initial"),
        ("users", "0002_address"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="collection_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_address",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.address",
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts",
                to="shipping.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="checkoutline",
            name="checkout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="checkout.checkout",
            ),
        ),
        migrations.AddField(
            model_name="checkoutmetadata",
            name="checkout",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_storage",
                to="checkout.checkout",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="checkoutline_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutline",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="checkoutline_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutmetadata",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="checkoutmetadata_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutmetadata",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="checkoutmetadata_meta_idx"
            ),
        ),
    ]
