# Generated by Django 5.0.8 on 2024-08-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_initial"),
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutline",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="product.productvariant",
            ),
            preserve_default=False,
        ),
    ]
