# Generated by Django 4.2.2 on 2023-07-14 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_index_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmedia",
            name="to_remove",
        ),
    ]
