# Generated by Django 4.2.2 on 2023-07-14 19:54

from django.db import migrations
import django_measurement.models
import measurement.measures.mass
import snap_buy.core.weight


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_productmedia_to_remove"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="weight",
            field=django_measurement.models.MeasurementField(
                blank=True,
                default=snap_buy.core.weight.zero_weight,
                measurement=measurement.measures.mass.Mass,
                null=True,
            ),
        ),
    ]
