# Generated by Django 5.0.8 on 2024-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("subscription_query", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
