# Generated by Django 5.0.8 on 2024-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="name",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webhook",
            name="secret_key",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="webhook",
            name="subscription_query",
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
