# Generated by Django 5.0.8 on 2024-08-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0003_productchannellisting_product_pro_publish_a3c049_idx_and_more",
        ),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="excluded_products",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
    ]
