# Generated by Django 5.0.8 on 2024-08-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0002_initial"),
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionrule",
            name="gifts",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="product.productvariant"
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="variants",
            field=models.ManyToManyField(
                blank=True,
                through="discount.PromotionRule_Variants",
                to="product.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="promotionrule_variants",
            name="productvariant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productvariant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voucher",
            name="categories",
            field=models.ManyToManyField(blank=True, to="product.category"),
        ),
        migrations.AddField(
            model_name="voucher",
            name="collections",
            field=models.ManyToManyField(blank=True, to="product.collection"),
        ),
        migrations.AddField(
            model_name="voucher",
            name="products",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
        migrations.AddField(
            model_name="voucher",
            name="variants",
            field=models.ManyToManyField(blank=True, to="product.productvariant"),
        ),
    ]
