# Generated by Django 4.2.2 on 2023-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("ar", "Arabic"),
                    ("ar-eg", "Arabic (Egypt)"),
                    ("en", "English"),
                    ("en-us", "English (United States)"),
                ],
                default="en-us",
                max_length=35,
            ),
        ),
    ]
